- name: Añadiendo clave pública ssh
  template:
    src: authorized_keys
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: '0600'
- name: Añadiendo:Bit de forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes

- name: Cambiando el archivo /etc/network/interfaces
  template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciando la maquina


